### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by koleini** [mirage/ocaml-vchan#61]
Errors arise when installing vchan (opam 1.2.0):

\# opam-version 1.2.0
\# os           linux
\# command      make build
\# path         /home/.opam/4.01.0/build/vchan.2.0.0
\# compiler     4.01.0
\# exit-code    2
\# env-file     /home/.opam/4.01.0/build/vchan.2.0.0/vchan-27375-d2c37b.env
\# stdout-file  /home/.opam/4.01.0/build/vchan.2.0.0/vchan-27375-d2c37b.out
\# stderr-file  /home/.opam/4.01.0/build/vchan.2.0.0/vchan-27375-d2c37b.err
\#\#\# stdout \#\#\#
\# Looking for xenctrl.h: ok
\#\#\# stderr \#\#\#
\# ...[truncated]
\# W: Field 'pkg_xen_evtchn_unix' is not set: Command ''/home/.opam/4.01.0/bin/ocamlfind' query -format %d xen-evtchn.unix > '/tmp/oasis-5ae306.txt'' terminated with error code 2
\# ocamlfind: Package `xen-evtchn.unix.activations' not found
\# W: Field 'pkg_xen_evtchn_unix_activations' is not set: Command ''/home/.opam/4.01.0/bin/ocamlfind' query -format %d xen-evtchn.unix.activations > '/tmp/oasis-f36d99.txt'' terminated with error code 2
\# ocamlfind: Package `xen-gnt.unix' not found
\# W: Field 'pkg_xen_gnt_unix' is not set: Command ''/home/.opam/4.01.0/bin/ocamlfind' query -format %d xen-gnt.unix > '/tmp/oasis-e5532b.txt'' terminated with error code 2
\# E: Cannot find findlib package xen-evtchn.unix
\# E: Cannot find findlib package xen-evtchn.unix.activations
\# E: Cannot find findlib package xen-gnt.unix
\# E: Failure("3 configuration errors")
\# make: *** [setup.data] Error 1

**Comment by djs55** [comment]
Could you post the output of "ocamlfind list"?

On Thu, Jan 15, 2015 at 12:31 PM, Masoud Koleini <notifications@github.com>
wrote:

> Errors arise when installing vchan (opam 1.2.0):
>
> #=== ERROR while installing vchan.2.0.0
> =======================================#
> opam-version 1.2.0 os linux command make build path
> /home/.opam/4.01.0/build/vchan.2.0.0 compiler 4.01.0 exit-code 2 env-file
> /home/.opam/4.01.0/build/vchan.2.0.0/vchan-27375-d2c37b.env stdout-file
> /home/.opam/4.01.0/build/vchan.2.0.0/vchan-27375-d2c37b.out stderr-file
> /home/.opam/4.01.0/build/vchan.2.0.0/vchan-27375-d2c37b.err stdout Looking
> for xenctrl.h: ok stderr ...[truncated] W: Field 'pkg_xen_evtchn_unix' is
> not set: Command ''/home/.opam/4.01.0/bin/ocamlfind' query -format %d
> xen-evtchn.unix > '/tmp/oasis-5ae306.txt'' terminated with error code 2 ocamlfind:
> Package `xen-evtchn.unix.activations' not found W: Field
> 'pkg_xen_evtchn_unix_activations' is not set: Command
> ''/home/.opam/4.01.0/bin/ocamlfind' query -format %d
> xen-evtchn.unix.activations > '/tmp/oasis-f36d99.txt'' terminated with
> error code 2 ocamlfind: Package `xen-gnt.unix' not found W: Field
> 'pkg_xen_gnt_unix' is not set: Command ''/home/.opam/4.01.0/bin/ocamlfind'
> query -format %d xen-gnt.unix > '/tmp/oasis-e5532b.txt'' terminated with
> error code 2 E: Cannot find findlib package xen-evtchn.unix E: Cannot
> find findlib package xen-evtchn.unix.activations E: Cannot find findlib
> package xen-gnt.unix E: Failure("3 configuration errors") make: ***
> [setup.data] Error 1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/ocaml-vchan/issues/61>.
>



-- 
Dave Scott

**Comment by koleini** [comment]
async               (version: 111.25.00)
async_extra         (version: 111.28.00)
async_kernel        (version: 111.28.00)
async_unix          (version: 111.28.00)
bigarray            (version: [distributed with Ocaml])
bin_prot            (version: 111.03.00)
bin_prot.syntax     (version: 111.03.00)
biniou              (version: 1.0.9)
bytes               (version: [OCaml strictly before 4.02])
camlp4              (version: [distributed with Ocaml])
camlp4.exceptiontracer (version: [distributed with Ocaml])
camlp4.extend       (version: [distributed with Ocaml])
camlp4.foldgenerator (version: [distributed with Ocaml])
camlp4.fulllib      (version: [distributed with Ocaml])
camlp4.gramlib      (version: [distributed with Ocaml])
camlp4.lib          (version: [distributed with Ocaml])
camlp4.listcomprehension (version: [distributed with Ocaml])
camlp4.locationstripper (version: [distributed with Ocaml])
camlp4.macro        (version: [distributed with Ocaml])
camlp4.mapgenerator (version: [distributed with Ocaml])
camlp4.metagenerator (version: [distributed with Ocaml])
camlp4.profiler     (version: [distributed with Ocaml])
camlp4.quotations   (version: [distributed with Ocaml])
camlp4.quotations.o (version: [distributed with Ocaml])
camlp4.quotations.r (version: [distributed with Ocaml])
camlp4.tracer       (version: [distributed with Ocaml])
cmdliner            (version: 0.9.6)
comparelib          (version: 109.60.00)
comparelib.syntax   (version: 109.60.00)
compiler-libs       (version: [distributed with Ocaml])
compiler-libs.bytecomp (version: [distributed with Ocaml])
compiler-libs.common (version: [distributed with Ocaml])
compiler-libs.optcomp (version: [distributed with Ocaml])
compiler-libs.toplevel (version: [distributed with Ocaml])
core                (version: 111.28.01)
core.syntax         (version: 109.32.00)
core.top            (version: 111.28.01)
core_kernel         (version: 111.28.00)
core_kernel.check_caml_modify (version: 111.28.00)
core_kernel.raise_without_backtrace (version: 111.28.00)
cppo_ocamlbuild     (version: 1.1.2)
crunch              (version: 1.1.0)
cstruct             (version: 1.5.0)
cstruct.async       (version: 1.5.0)
cstruct.lwt         (version: 1.5.0)
cstruct.syntax      (version: 1.5.0)
cstruct.unix        (version: 1.5.0)
custom_printf       (version: 111.25.00)
custom_printf.syntax (version: 111.25.00)
dynlink             (version: [distributed with Ocaml])
easy-format         (version: 1.0.2)
enumerate           (version: n/a)
enumerate.syntax    (version: 111.08.00)
fieldslib           (version: 109.20.03)
fieldslib.syntax    (version: 109.20.03)
findlib             (version: 1.5.5)
graphics            (version: [distributed with Ocaml])
herelib             (version: 109.35.02)
herelib.syntax      (version: 109.35.02)
io-page             (version: 1.2.0)
io-page.unix        (version: 1.2.0)
ipaddr              (version: 2.5.0)
ipaddr.top          (version: 2.5.0)
ipaddr.unix         (version: 2.5.0)
lwt                 (version: 2.4.6)
lwt.extra           (version: 2.4.6)
lwt.log             (version: 2.4.6)
lwt.preemptive      (version: 2.4.6)
lwt.simple-top      (version: 2.4.6)
lwt.syntax          (version: 2.4.6)
lwt.syntax.log      (version: 2.4.6)
lwt.syntax.options  (version: 2.4.6)
lwt.tracing         (version: 2.4.6)
lwt.unix            (version: 2.4.6)
mirage              (version: 2.2.1)
mirage-clock-unix   (version: 1.0.0)
mirage-clock-xen    (version: 1.0.0)
mirage-console      (version: 2.1.0)
mirage-console.proto (version: 2.1.0)
mirage-console.unix (version: 2.1.0)
mirage-console.xen  (version: 2.1.0)
mirage-net-unix     (version: 1.1.1)
mirage-net-xen      (version: 1.2.0)
mirage-profile      (version: 0.1)
mirage-profile.unix (version: 0.1)
mirage-profile.xen  (version: 0.1)
mirage-types        (version: 2.2.0)
mirage-types.lwt    (version: 2.2.0)
mirage-unix         (version: 2.1.2)
mirage-xen          (version: 2.1.2)
mirage.runtime      (version: 2.2.1)
netkat              (version: 3.1.0)
netkat.async        (version: 3.1.0)
netkat.quickcheck   (version: 3.1.0)
netkat.syntax       (version: 3.1.0)
num                 (version: [distributed with Ocaml])
num-top             (version: 1.5.5)
num.core            (version: [internal])
oUnit               (version: 2.0.0)
oUnit.advanced      (version: 2.0.0)
oUnit.threads       (version: 2.0.0)
oasis               (version: 0.4.5)
oasis.base          (version: 0.4.5)
oasis.builtin-plugins (version: 0.4.5)
oasis.cli           (version: 0.4.5)
oasis.dynrun        (version: 0.4.5)
ocamlbuild          (version: [distributed with Ocaml])
ocamlgraph          (version: 1.8.5)
ocplib-endian       (version: 0.8)
ocplib-endian.bigstring (version: 0.8)
odn                 (version: 0.0.11)
odn.with            (version: n/a)
odn.with.syntax     (version: 0.0.11)
odn.without         (version: n/a)
odn.without.syntax  (version: 0.0.11)
openflow            (version: 0.7.0)
openflow.async      (version: 0.7.0)
openflow.quickcheck (version: 0.7.0)
optcomp             (version: 1.6)
pa_bench            (version: 111.28.00)
pa_bench.syntax     (version: 111.28.00)
pa_ounit            (version: 111.28.00)
pa_ounit.syntax     (version: 111.28.00)
pa_pipebang         (version: 110.01.00)
pa_test             (version: 111.08.00)
pa_test.syntax      (version: 111.08.00)
packet              (version: 0.3.1)
packet.quickcheck   (version: 0.3.1)
plugin-loader       (version: 0.4.5)
quickcheck          (version: 1.0.2)
re                  (version: 1.2.1)
re.emacs            (version: 1.2.1)
re.glob             (version: 1.2.1)
re.pcre             (version: 1.2.1)
re.perl             (version: 1.2.1)
re.posix            (version: 1.2.1)
re.str              (version: 1.2.1)
sexplib             (version: 111.25.00)
sexplib.syntax      (version: 111.25.00)
sexplib.top         (version: 111.25.00)
sexplib_num         (version: 111.25.00)
sexplib_unix        (version: 111.25.00)
shared-memory-ring  (version: 1.1.1)
shared-memory-ring.console (version: 1.1.1)
shared-memory-ring.lwt (version: 1.1.1)
shared-memory-ring.xenstore (version: 1.1.1)
stdlib              (version: [distributed with Ocaml])
str                 (version: [distributed with Ocaml])
stringext           (version: 1.2.0)
tcpip               (version: 2.2.2)
tcpip.channel       (version: 2.2.2)
tcpip.dhcpv4        (version: 2.2.2)
tcpip.ethif         (version: 2.2.2)
tcpip.ethif-unix    (version: 2.2.2)
tcpip.ipv4          (version: 2.2.2)
tcpip.ipv4-unix     (version: 2.2.2)
tcpip.ipv6          (version: 2.2.2)
tcpip.ipv6-unix     (version: 2.2.2)
tcpip.stack-direct  (version: 2.2.2)
tcpip.stack-socket  (version: 2.2.2)
tcpip.stack-unix    (version: 2.2.2)
tcpip.tcp           (version: 2.2.2)
tcpip.tcpv4-socket  (version: 2.2.2)
tcpip.tcpv4-unix    (version: 2.2.2)
tcpip.tcpv6-socket  (version: 2.2.2)
tcpip.tcpv6-unix    (version: 2.2.2)
tcpip.udp           (version: 2.2.2)
tcpip.udpv4-socket  (version: 2.2.2)
tcpip.udpv4-unix    (version: 2.2.2)
tcpip.udpv6-socket  (version: 2.2.2)
tcpip.udpv6-unix    (version: 2.2.2)
tcpip.xen           (version: 2.2.2)
tdk                 (version: 0.1.1)
threads             (version: [distributed with Ocaml])
threads.posix       (version: [internal])
threads.vm          (version: [internal])
topology            (version: 0.2.0)
tuntap              (version: 1.0.0)
type_conv           (version: 111.13.00)
typerep_extended    (version: 111.17.00)
typerep_generics_sexprep (version: 111.17.00)
typerep_lib         (version: 111.17.00)
typerep_lib.syntax  (version: 111.17.00)
uint                (version: 1.1.5)
uint.uint128        (version: 1.1.5)
uint.uint32         (version: 1.1.5)
uint.uint64         (version: 1.1.5)
ulex                (version: 1.1)
unix                (version: [distributed with Ocaml])
uri                 (version: 1.7.2)
uri.services        (version: 1.7.2)
uri.top             (version: 1.7.2)
userconf            (version: 0.4.5)
variantslib         (version: 109.15.03)
variantslib.syntax  (version: 109.15.03)
xen-evtchn          (version: 1.0.5)
xen-gnt             (version: 2.1.0)
xenstore            (version: 1.2.5)
xenstore.client     (version: 1.2.5)
xenstore.server     (version: 1.2.5)
xenstore.unix       (version: 1.2.5)
xenstore_transport  (version: 0.9.4)
xenstore_transport.lwt (version: 0.9.4)
xenstore_transport.unix (version: 0.9.4)
yojson              (version: 1.2.0)
yojson.biniou       (version: 1.2.0)

**Comment by djs55** [comment]
```
xen-evtchn (version: 1.0.5)
xen-gnt (version: 2.1.0)
```
I think this means that your xen-evtchn and xen-gnt were built when
xenctrl.h was not installed. Assuming it has been installed since, try
reinstalling these two packages.

On Thu, Jan 15, 2015 at 12:35 PM, Masoud Koleini <notifications@github.com>
wrote:

> async (version: 111.25.00)
> async_extra (version: 111.28.00)
> async_kernel (version: 111.28.00)
> async_unix (version: 111.28.00)
> bigarray (version: [distributed with Ocaml])
> bin_prot (version: 111.03.00)
> bin_prot.syntax (version: 111.03.00)
> biniou (version: 1.0.9)
> bytes (version: [OCaml strictly before 4.02])
> camlp4 (version: [distributed with Ocaml])
> camlp4.exceptiontracer (version: [distributed with Ocaml])
> camlp4.extend (version: [distributed with Ocaml])
> camlp4.foldgenerator (version: [distributed with Ocaml])
> camlp4.fulllib (version: [distributed with Ocaml])
> camlp4.gramlib (version: [distributed with Ocaml])
> camlp4.lib (version: [distributed with Ocaml])
> camlp4.listcomprehension (version: [distributed with Ocaml])
> camlp4.locationstripper (version: [distributed with Ocaml])
> camlp4.macro (version: [distributed with Ocaml])
> camlp4.mapgenerator (version: [distributed with Ocaml])
> camlp4.metagenerator (version: [distributed with Ocaml])
> camlp4.profiler (version: [distributed with Ocaml])
> camlp4.quotations (version: [distributed with Ocaml])
> camlp4.quotations.o (version: [distributed with Ocaml])
> camlp4.quotations.r (version: [distributed with Ocaml])
> camlp4.tracer (version: [distributed with Ocaml])
> cmdliner (version: 0.9.6)
> comparelib (version: 109.60.00)
> comparelib.syntax (version: 109.60.00)
> compiler-libs (version: [distributed with Ocaml])
> compiler-libs.bytecomp (version: [distributed with Ocaml])
> compiler-libs.common (version: [distributed with Ocaml])
> compiler-libs.optcomp (version: [distributed with Ocaml])
> compiler-libs.toplevel (version: [distributed with Ocaml])
> core (version: 111.28.01)
> core.syntax (version: 109.32.00)
> core.top (version: 111.28.01)
> core_kernel (version: 111.28.00)
> core_kernel.check_caml_modify (version: 111.28.00)
> core_kernel.raise_without_backtrace (version: 111.28.00)
> cppo_ocamlbuild (version: 1.1.2)
> crunch (version: 1.1.0)
> cstruct (version: 1.5.0)
> cstruct.async (version: 1.5.0)
> cstruct.lwt (version: 1.5.0)
> cstruct.syntax (version: 1.5.0)
> cstruct.unix (version: 1.5.0)
> custom_printf (version: 111.25.00)
> custom_printf.syntax (version: 111.25.00)
> dynlink (version: [distributed with Ocaml])
> easy-format (version: 1.0.2)
> enumerate (version: n/a)
> enumerate.syntax (version: 111.08.00)
> fieldslib (version: 109.20.03)
> fieldslib.syntax (version: 109.20.03)
> findlib (version: 1.5.5)
> graphics (version: [distributed with Ocaml])
> herelib (version: 109.35.02)
> herelib.syntax (version: 109.35.02)
> io-page (version: 1.2.0)
> io-page.unix (version: 1.2.0)
> ipaddr (version: 2.5.0)
> ipaddr.top (version: 2.5.0)
> ipaddr.unix (version: 2.5.0)
> lwt (version: 2.4.6)
> lwt.extra (version: 2.4.6)
> lwt.log (version: 2.4.6)
> lwt.preemptive (version: 2.4.6)
> lwt.simple-top (version: 2.4.6)
> lwt.syntax (version: 2.4.6)
> lwt.syntax.log (version: 2.4.6)
> lwt.syntax.options (version: 2.4.6)
> lwt.tracing (version: 2.4.6)
> lwt.unix (version: 2.4.6)
> mirage (version: 2.2.1)
> mirage-clock-unix (version: 1.0.0)
> mirage-clock-xen (version: 1.0.0)
> mirage-console (version: 2.1.0)
> mirage-console.proto (version: 2.1.0)
> mirage-console.unix (version: 2.1.0)
> mirage-console.xen (version: 2.1.0)
> mirage-net-unix (version: 1.1.1)
> mirage-net-xen (version: 1.2.0)
> mirage-profile (version: 0.1)
> mirage-profile.unix (version: 0.1)
> mirage-profile.xen (version: 0.1)
> mirage-types (version: 2.2.0)
> mirage-types.lwt (version: 2.2.0)
> mirage-unix (version: 2.1.2)
> mirage-xen (version: 2.1.2)
> mirage.runtime (version: 2.2.1)
> netkat (version: 3.1.0)
> netkat.async (version: 3.1.0)
> netkat.quickcheck (version: 3.1.0)
> netkat.syntax (version: 3.1.0)
> num (version: [distributed with Ocaml])
> num-top (version: 1.5.5)
> num.core (version: [internal])
> oUnit (version: 2.0.0)
> oUnit.advanced (version: 2.0.0)
> oUnit.threads (version: 2.0.0)
> oasis (version: 0.4.5)
> oasis.base (version: 0.4.5)
> oasis.builtin-plugins (version: 0.4.5)
> oasis.cli (version: 0.4.5)
> oasis.dynrun (version: 0.4.5)
> ocamlbuild (version: [distributed with Ocaml])
> ocamlgraph (version: 1.8.5)
> ocplib-endian (version: 0.8)
> ocplib-endian.bigstring (version: 0.8)
> odn (version: 0.0.11)
> odn.with (version: n/a)
> odn.with.syntax (version: 0.0.11)
> odn.without (version: n/a)
> odn.without.syntax (version: 0.0.11)
> openflow (version: 0.7.0)
> openflow.async (version: 0.7.0)
> openflow.quickcheck (version: 0.7.0)
> optcomp (version: 1.6)
> pa_bench (version: 111.28.00)
> pa_bench.syntax (version: 111.28.00)
> pa_ounit (version: 111.28.00)
> pa_ounit.syntax (version: 111.28.00)
> pa_pipebang (version: 110.01.00)
> pa_test (version: 111.08.00)
> pa_test.syntax (version: 111.08.00)
> packet (version: 0.3.1)
> packet.quickcheck (version: 0.3.1)
> plugin-loader (version: 0.4.5)
> quickcheck (version: 1.0.2)
> re (version: 1.2.1)
> re.emacs (version: 1.2.1)
> re.glob (version: 1.2.1)
> re.pcre (version: 1.2.1)
> re.perl (version: 1.2.1)
> re.posix (version: 1.2.1)
> re.str (version: 1.2.1)
> sexplib (version: 111.25.00)
> sexplib.syntax (version: 111.25.00)
> sexplib.top (version: 111.25.00)
> sexplib_num (version: 111.25.00)
> sexplib_unix (version: 111.25.00)
> shared-memory-ring (version: 1.1.1)
> shared-memory-ring.console (version: 1.1.1)
> shared-memory-ring.lwt (version: 1.1.1)
> shared-memory-ring.xenstore (version: 1.1.1)
> stdlib (version: [distributed with Ocaml])
> str (version: [distributed with Ocaml])
> stringext (version: 1.2.0)
> tcpip (version: 2.2.2)
> tcpip.channel (version: 2.2.2)
> tcpip.dhcpv4 (version: 2.2.2)
> tcpip.ethif (version: 2.2.2)
> tcpip.ethif-unix (version: 2.2.2)
> tcpip.ipv4 (version: 2.2.2)
> tcpip.ipv4-unix (version: 2.2.2)
> tcpip.ipv6 (version: 2.2.2)
> tcpip.ipv6-unix (version: 2.2.2)
> tcpip.stack-direct (version: 2.2.2)
> tcpip.stack-socket (version: 2.2.2)
> tcpip.stack-unix (version: 2.2.2)
> tcpip.tcp (version: 2.2.2)
> tcpip.tcpv4-socket (version: 2.2.2)
> tcpip.tcpv4-unix (version: 2.2.2)
> tcpip.tcpv6-socket (version: 2.2.2)
> tcpip.tcpv6-unix (version: 2.2.2)
> tcpip.udp (version: 2.2.2)
> tcpip.udpv4-socket (version: 2.2.2)
> tcpip.udpv4-unix (version: 2.2.2)
> tcpip.udpv6-socket (version: 2.2.2)
> tcpip.udpv6-unix (version: 2.2.2)
> tcpip.xen (version: 2.2.2)
> tdk (version: 0.1.1)
> threads (version: [distributed with Ocaml])
> threads.posix (version: [internal])
> threads.vm (version: [internal])
> topology (version: 0.2.0)
> tuntap (version: 1.0.0)
> type_conv (version: 111.13.00)
> typerep_extended (version: 111.17.00)
> typerep_generics_sexprep (version: 111.17.00)
> typerep_lib (version: 111.17.00)
> typerep_lib.syntax (version: 111.17.00)
> uint (version: 1.1.5)
> uint.uint128 (version: 1.1.5)
> uint.uint32 (version: 1.1.5)
> uint.uint64 (version: 1.1.5)
> ulex (version: 1.1)
> unix (version: [distributed with Ocaml])
> uri (version: 1.7.2)
> uri.services (version: 1.7.2)
> uri.top (version: 1.7.2)
> userconf (version: 0.4.5)
> variantslib (version: 109.15.03)
> variantslib.syntax (version: 109.15.03)
> xen-evtchn (version: 1.0.5)
> xen-gnt (version: 2.1.0)
> xenstore (version: 1.2.5)
> xenstore.client (version: 1.2.5)
> xenstore.server (version: 1.2.5)
> xenstore.unix (version: 1.2.5)
> xenstore_transport (version: 0.9.4)
> xenstore_transport.lwt (version: 0.9.4)
> xenstore_transport.unix (version: 0.9.4)
> yojson (version: 1.2.0)
> yojson.biniou (version: 1.2.0)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/ocaml-vchan/issues/61#issuecomment-70079450>.
>



-- 
Dave Scott

**Comment by koleini** [comment]
Worked, thanks.

**Comment by djs55** [comment]
OK, good to hear. Let's leave this issue open and fix it by improving the
error message: the configure script could have helped here

On Thu, Jan 15, 2015 at 12:47 PM, Masoud Koleini <notifications@github.com>
wrote:

> Worked, thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/ocaml-vchan/issues/61#issuecomment-70080728>.
>



-- 
Dave Scott
