### ISSUE TITLE
Failed to open event channel interface: ENOENT

### ISSUE THREAD

**Issue by talex5** [mirage/ocaml-vchan#66]
I'm writing a Mirage web-server. Every time it starts under unix, it prints this warning:

    Failed to open event channel interface: ENOENT
    Does this system have Xen userspace eventchannel support?
    On linux try:
      sudo modprobe xen-evtchn

It appears that merely having the `Unix_activations` module linked in causes this, even if event channels are not actually used, due to the `activations_thread` global being statically initialised. It would be better if we could avoid this warning when event channels aren't being used.

**Comment by avsm** [comment]
dup of mirage/ocaml-gnt#14

**Comment by djs55** [comment]
heh ok, at least it gives the user some helpful advice ;)

On Fri, Feb 13, 2015 at 12:14 PM, Anil Madhavapeddy <
notifications@github.com> wrote:

> dup of mirage/ocaml-gnt#14 <https://github.com/mirage/ocaml-gnt/issues/14>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/ocaml-vchan/issues/66#issuecomment-74245137>.
>



-- 
Dave Scott

**Comment by djs55** [comment]
OK, this is fixed in [mirage/ocaml-evtchn#19], released in xen-evtchn.1.0.6 [ocaml/opam-repository#3587]
