### ISSUE TITLE
Support lwt 2.5.0

### ISSUE THREAD

**Issue by samoht** [mirage/ocaml-vchan#75]
Related to https://github.com/ocaml/opam-repository/pull/4480

**Comment by samoht** [comment]
@djs55 do you have time to look at that by any chance?

**Comment by djs55** [comment]
Sorry for the delay, pull request created!

On Thu, Sep 3, 2015 at 8:08 PM, Thomas Gazagnaire <notifications@github.com>
wrote:

> @djs55 <https://github.com/djs55> do you have time to look at that by any
> chance?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/ocaml-vchan/issues/75#issuecomment-137544537>.
>



-- 
Dave Scott

**Comment by djs55** [comment]
[ocaml/opam-repository#4772]
