### ISSUE TITLE
install seems to fail on fedora 24

### ISSUE THREAD

**Issue by yomimono** [mirage/ocaml-vchan#89]
See https://travis-ci.org/mirage/mirage/jobs/167401772#L5506 .

**Comment by talex5** [comment]
To aid searching, etc, the error is:
```
#=== ERROR while installing vchan.2.2.0 =======================================#
# opam-version         1.2.2 (58ef3b8213100953848d362f7120a30356d7f77d)
# os                   linux
# command              ./configure --enable-xenctrl --enable-xen
# path                 /home/opam/.opam/system/build/vchan.2.2.0
# compiler             system (4.02.3)
# exit-code            1
# env-file             /home/opam/.opam/system/build/vchan.2.2.0/vchan-825-0560c0.env
# stdout-file          /home/opam/.opam/system/build/vchan.2.2.0/vchan-825-0560c0.out
# stderr-file          /home/opam/.opam/system/build/vchan.2.2.0/vchan-825-0560c0.err
### stdout ###
# Looking for xenctrl.h: missing
### stderr ###
# Error: xenctrl has unsatisfied dependencies but has been requested via the command-line
# If you installed the xenctrl.h header file after installing OCaml packages, try reinstalling the OCaml packages via:
#   opam reinstall xen-evtchn xen-gnt
```

**Comment by talex5** [comment]
Here's a similar failure on Ubuntu 12.04.5:

https://travis-ci.org/talex5/mirage-qubes/builds/174556796

**Comment by hannesm** [comment]
@talex5 your build failure might be related to `sudo` not being enabled, and thus opam depext not being able to install system packages (libxen_whatever)? (see the head of the log you linked to)

**Comment by djs55** [comment]
The ocaml-vchan CI now installs on Fedora-24. The package `xen-devel` which includes `xenctrl.h` will be brought in as a depext of the new dependencies `xen-{evtchn,gnt}-unix`, see https://github.com/ocaml/opam-repository/pull/9352

I think this should be fixed now.
